Больше деталей
htmlacademy-javascript/1382357-kekstagram-28 pull request #3
Opened 2023-02-24 17:32 UTC by JuliaNik22

2023-02-26 05:27 UTC, nzhorn requested changes

2023-02-26 05:27 UTC, nzhorn commented on js/main.js
> +    const COMMENTS = {
Сейчас получается ситуация при которой все комментарии одинаковые(
<img width="469" alt="Снимок экрана 2023-02-26 в 12 25 57" src="https://user-images.githubusercontent.com/19977052/221393930-95f54547-5665-4500-a26d-bb7577695053.png">

2023-02-26 14:38 UTC, JuliaNik22 commented on js/main.js
> +    const COMMENTS = {
Нашла причину бага: индексы для сообщения и имени комментария надо было задавать в цикле, а я задавала перед циклом. Исправила)

2023-02-27 03:38 UTC, nzhorn approved these changes

2023-02-27 03:38 UTC, merged